Day 3 (WIP)

diff --git a/startday-python b/startday-python
--- a/startday-python
+++ b/startday-python
@@ -8,6 +8,10 @@ if ! [[ $DAY =~ $re ]] ; then
    echo "Error: Not a number" >&2; exit 1
 fi
 
+if ((DAY < 1 || DAY > 25)); then
+    echo "Invalid day input: $1. Must be between 1 and 25." >&2; exit 1
+fi
+
 if test -f "python/day${DAY}.py"; then
    echo "Error: day${DAY}.py already exists !" >&2; exit 2
 fi
